spring:
  boot:
    message: Hello, Department Service updated
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: 1003
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: DEPARTMENT-SERVICE
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
